/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.EmployeeProfile;
import model.EmployeeProfileHistory;

/**
 *
 * @author leonardodicaprio
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    String filename = null;
    byte[] person_photo = null;
//    EmployeeProfile employeeProfile;
    EmployeeProfileHistory history;
    
    public CreateJPanel(EmployeeProfileHistory history) {
        initComponents();
        this.history = history;
//        this.employeeProfile = employeeProfile;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCreate = new javax.swing.JLabel();
        jphoto = new javax.swing.JLabel();
        jBChoose = new javax.swing.JButton();
        jName = new javax.swing.JLabel();
        jE_ID = new javax.swing.JLabel();
        jAge = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jStartDate = new javax.swing.JLabel();
        jLevel = new javax.swing.JLabel();
        jTeamInfo = new javax.swing.JLabel();
        jPositionTitle = new javax.swing.JLabel();
        jCellPhoneNumber = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jTextEmployeeID = new javax.swing.JTextField();
        jTextAge = new javax.swing.JTextField();
        jTextGender = new javax.swing.JTextField();
        jTextStartDate = new javax.swing.JTextField();
        jTextLevel = new javax.swing.JTextField();
        jTextTeam = new javax.swing.JTextField();
        jTextPositionTitle = new javax.swing.JTextField();
        jTextCellPhone = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jBSave = new javax.swing.JButton();

        jCreate.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCreate.setText("Create Employee Profile");

        jphoto.setText("Photo");

        jBChoose.setText("Choose");
        jBChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChooseActionPerformed(evt);
            }
        });

        jName.setText("Name");

        jE_ID.setText("Employee ID");

        jAge.setText("Age");

        jGender.setText("Gender");

        jStartDate.setText("Start Date");

        jLevel.setText("Level");

        jTeamInfo.setText("Team Info");

        jPositionTitle.setText("Position Title");

        jCellPhoneNumber.setText("Cell Phone Number");

        jEmail.setText("Email Address");

        jBSave.setText("Save");
        jBSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jE_ID)
                    .addComponent(jStartDate)
                    .addComponent(jGender)
                    .addComponent(jAge)
                    .addComponent(jName)
                    .addComponent(jphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jBChoose))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextGender)
                                    .addComponent(jTextStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(jTextAge, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addComponent(jLevel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jTeamInfo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPositionTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCellPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jEmail, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jTextTeam)
                            .addComponent(jTextPositionTitle)
                            .addComponent(jTextCellPhone)
                            .addComponent(jTextEmail))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSave)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jCreate)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jphoto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jBChoose)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jLevel)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jE_ID)
                    .addComponent(jTeamInfo)
                    .addComponent(jTextEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge)
                    .addComponent(jPositionTitle)
                    .addComponent(jTextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGender)
                    .addComponent(jCellPhoneNumber)
                    .addComponent(jTextGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStartDate)
                    .addComponent(jEmail)
                    .addComponent(jTextStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSaveActionPerformed
        // TODO add your handling code here:
        
        String name = jTextName.getText();
        String id = jTextEmployeeID.getText();
        String age = jTextAge.getText();
        String gender = jTextGender.getText();
        String startDate = jTextStartDate.getText();
        String level = jTextLevel.getText();
        String teamInfo = jTextTeam.getText();
        String positionTitle = jTextPositionTitle.getText();
        String cellPhoneNumber = jTextCellPhone.getText();
        String emailAddress = jTextEmail.getText();
        
        EmployeeProfile ep = history.getCurrentEmployeeProfile();
        ep.setName(name);
        ep.setId(id);
        ep.setAge(age);
        ep.setGender(gender);
        ep.setStartDate(startDate);
        ep.setLevel(level);
        ep.setTeamInfo(teamInfo);
        ep.setPositionTitle(positionTitle);
        ep.setContactInfo1(cellPhoneNumber);
        ep.setContactInfo2(emailAddress);
        
        history.addNewEmployee(ep);
        
        JOptionPane.showMessageDialog(this, "New Employee Added!");
        
        jTextName.setText("");
        jTextEmployeeID.setText("");
        jTextAge.setText("");
        jTextGender.setText("");
        jTextStartDate.setText("");
        jTextLevel.setText("");
        jTextTeam.setText("");
        jTextPositionTitle.setText("");
        jTextCellPhone.setText("");
        jTextEmail.setText("");
        jphoto.setIcon(null);
        
        history.createNewEmployee();
        
    }//GEN-LAST:event_jBSaveActionPerformed

    private void jBChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChooseActionPerformed
        // TODO add your handling code here:
        
        JFileChooser cf = new JFileChooser();
        cf.showOpenDialog(null);
        File file = cf.getSelectedFile();
        
        if(file == null) {
            // if user do not select any picture, file woule be null.
            return;
        }
        
        filename = file.getAbsolutePath(); 
        
        history.getCurrentEmployeeProfile().setPhotoUrl(filename);
        
//        employeeProfile.setPhotoUrl(filename);
        
        ImageIcon imi = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(jphoto.getWidth(), jphoto.getHeight(), Image.SCALE_SMOOTH));
        jphoto.setIcon(imi);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            byte[] b = new byte[1024];
            for(int readNum;(readNum=fis.read(b))!=-1;){
                baos.write(b,0,readNum);
            }
            person_photo = baos.toByteArray();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        
    }//GEN-LAST:event_jBChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JButton jBChoose;
    private javax.swing.JButton jBSave;
    private javax.swing.JLabel jCellPhoneNumber;
    private javax.swing.JLabel jCreate;
    private javax.swing.JLabel jE_ID;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPositionTitle;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel jTeamInfo;
    private javax.swing.JTextField jTextAge;
    private javax.swing.JTextField jTextCellPhone;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextEmployeeID;
    private javax.swing.JTextField jTextGender;
    private javax.swing.JTextField jTextLevel;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPositionTitle;
    private javax.swing.JTextField jTextStartDate;
    private javax.swing.JTextField jTextTeam;
    private javax.swing.JLabel jphoto;
    // End of variables declaration//GEN-END:variables
}
